// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzftggY6ADF73UiL-jnOsz2Xyu8Jm2_oE',
    appId: '1:230129002026:web:8d7c13dba5044eebd40553',
    messagingSenderId: '230129002026',
    projectId: 'test-23040',
    authDomain: 'test-23040.firebaseapp.com',
    databaseURL: 'https://test-23040.firebaseio.com',
    storageBucket: 'test-23040.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7tJMNkND-r46_csB9lphQ1vsrRu0P7bM',
    appId: '1:230129002026:android:15707409691e7971d40553',
    messagingSenderId: '230129002026',
    projectId: 'test-23040',
    databaseURL: 'https://test-23040.firebaseio.com',
    storageBucket: 'test-23040.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCntijtCPktFNs3a1adG7fipSOfgKX1iGM',
    appId: '1:230129002026:ios:9ad5dfab7bc6fadfd40553',
    messagingSenderId: '230129002026',
    projectId: 'test-23040',
    databaseURL: 'https://test-23040.firebaseio.com',
    storageBucket: 'test-23040.appspot.com',
    iosClientId: '230129002026-buf046bk0ql5dfujc0sgi0um5u0l2i26.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCntijtCPktFNs3a1adG7fipSOfgKX1iGM',
    appId: '1:230129002026:ios:e461a67dd4a314f3d40553',
    messagingSenderId: '230129002026',
    projectId: 'test-23040',
    databaseURL: 'https://test-23040.firebaseio.com',
    storageBucket: 'test-23040.appspot.com',
    iosClientId: '230129002026-trd0f8ldieagq6nl2lna21f210qr1cqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
